---
label: Services
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: image
  type: file
  config:
    maxSize: 64
  label: Image
- name: seo
  type: include
  config: {}
  template: seo
  label: SEO
pages:
- content/services/gardening.md
- content/services/junk-removal.md
- content/services/landscaping.md
- content/services/pavers.md
- content/services/tree-service.md
- content/services/water-installation.md
